site_name: Manual Books Tokoku

extra_css:
  - assets/css/extra.css

theme:
  name: material
  logo: "assets/img/logo.png"
  favicon: "assets/img/logo.png"
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - header.autohide
  social:
    - type: "github"
      link: "https://github.com/Baguspanji"

extra:
  generator: false

plugins:
  - search

# repo_name: "panduan-merchant"
# repo_url: "https://github.com/Baguspanji/panduan-merchant"
copyright: "Copyright &copy; 2020 - 2021 CV Juru Ketik Nusantara"
