site_name: Manual Book Tokoku

extra_css:
  - assets/css/extra.css

theme:
  name: material
  logo: "assets/img/logo.png"
  favicon: "assets/img/logo.png"
  language: id
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.expand
    - header.autohide
  social:
    - type: "github"
      link: "https://github.com/Baguspanji"

nav:
  - Beranda: index.md
  - Menu Utama:
      - menu_utama/header.md
      - menu_utama/home.md
      - menu_utama/footer.md
  - Menu Produk:
      - menu_produk/produk.md
      - menu_produk/detail.md
  - Menu Riwayat:
      - menu_riwayat/riwayat-nav.md
      - menu_riwayat/riwayat.md
  - Menu Keranjang:
      - menu_cart/cart-nav.md
      - menu_cart/cart.md
  - Cara Pemesanan:
      - pesan/pesan.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Baguspanji
    - icon: fontawesome/solid/paper-plane
      link: mailto:bagusp1805@gmail.com
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bagus-panji-8870211b5
    - icon: fontawesome/brands/whatsapp
      link: https://wa.me/6285785800430?

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

# repo_name: "panduan-merchant"
# repo_url: "https://github.com/Baguspanji/panduan-merchant"
copyright: "Copyright &copy; 2020 - 2021 CV Juru Ketik Nusantara"
